### ISSUE TITLE
DSInternals Views

### ISSUE THREAD

**Issue by MichaelGrafnetter** [r4wd3r/ADPWN#1]
Hi @r4wd3r , nice parser! I just discoveded it by accident.

Did you know that DSInternals can export hashes to different formats natively?

```powershell
Get-ADReplAccount ... | Format-Custom -View PWDump > secrets.pwdump
```

These are all the views that are currently implemented:
- PWDump
- JohnNT
- JohnNTHistory
- JohnLM
- Ophcrack
- HashcatNT
- HashcatNTHistory
- HashcatLM
- NTHash
- NTHashHistory
- LMHash

**Comment by r4wd3r** [comment]
Hi @MichaelGrafnetter! Thank you for clarifying.

I wrote this 2 years ago. At that time I was not aware of the DSInternals hashes exporting feature, that's why I created this simple python script.

DSInternals is such an amazing framework! You are doing a great contribution to the community with it!

**Comment by MichaelGrafnetter** [comment]
Glad you like it. Well, I see that I really need to improve documentation.
